### ISSUE TITLE
withInhabited is incoherent

### ISSUE THREAD

**Issue by treeowl** [konn/equational-reasoning-in-haskell#2]
If I write

```haskell
data Foo = Bar | Baz

instance Inhabited Foo where
  trivial = Bar

withInhabited Baz trivial
```

there is no guarantee about what the result will be, and it may depend on which optimizations GHC does. A much safer approach would be to follow `Data.Reflection.reify`:

```haskell
newtype Box s a = Box a
withInhabited :: a -> (forall s. Inhabited (Box s a) => Proxy s -> r) -> r
```

**Comment by konn** [comment]
Well, as an intended semantics, `trivial` should return a "generic" value of `a`, which means that one must not assume anything particular about `trivial`, except that it is indeed of type `a` and does not contain partial value.
This is a major difference between our `Inhabited` class and `Reifies` class from `reflection` package, where one might should pass-around the implicit configuration coherently.
So, incoherency doesn't matter here.

Does this make sense?
