### ISSUE TITLE
inaccurate version bounds in equational-reasoning-0.6.0.0

### ISSUE THREAD

**Issue by hvr** [konn/equational-reasoning-in-haskell#3]
As can be seen at

https://matrix.hackage.haskell.org/package/equational-reasoning@1549382814

the bounds for `template-haskell` seem to be inaccurate.

Also, looking at the code, 

```
#if defined(__GLASGOW_HASKELL__) && __GLASGOW_HASKELL__ < 804
fieldsVars (DNormalC fs)
#else
fieldsVars (DNormalC _ fs)
#endif
```

this ought to be expressed in terms of the respective `MIN_VERSION_th_desugar(_,_,_)` macro.

luckily, the `.cabal` file already had a matching conditional, so I was able to fix this up via a [Hackage metadata revision](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) by changing the bounds of `th-desugar` 
```
  if impl(ghc >= 8.4)
     build-depends:    th-desugar       >= 1.6 && < 1.11
  else
     build-depends:    th-desugar       >= 1.6 && < 1.11
     build-depends:    semigroups       == 0.18.*
```

into disjunctive ranges:

```
  if impl(ghc >= 8.4)
     build-depends:    th-desugar       >= 1.8 && < 1.11
  else
     build-depends:    th-desugar       >= 1.6 && < 1.8
     build-depends:    semigroups       == 0.18.*
```

(see also https://hackage.haskell.org/package/equational-reasoning-0.6.0.0/revisions/)

The resulting build-plan state can be inspected at https://matrix.hackage.haskell.org/package/equational-reasoning@1549441348

**Comment by konn** [comment]
@hvr Thank you for pointing it out and fixing it on the Hackage!
I will reflect your change to my `.cabal` file immediately. Thanks again!
